name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod

    - name: Set up go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod

