name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version-file: ${{ github.action_path }}/.nvmrc
    
